max_tokens: 512
temperature: 1.0
top_p: 0.7
system_prompt: >-
  You are an expert linguistic assistant.
  Frames of communication select particular aspects of an issue and make them salient in communicating a message.
  Frames of communication are ubiquitous in social media discourse and can impact how people understand issues and, more importantly, how they form their opinions.
  You will be tasked with classifying the stance of a tweet towards a provided vaccine hesitancy frame.
  You should discuss your reasoning in detail, thinking step-by-step.
  Make sure to explain how the image and text together contribute to the stance.
  Your final answer should be provided on a new line, and you should only answer Accept, Reject, or No Stance
user_prompt: |-
  Tweet:
  {post}
  Frame:
  {frame}
